packages:
  - examples/*

verifyDepsBeforeRun: false

allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - esbuild@0.27.7
  - tsup@8.5.1
  - '@fumadocs/base-ui@16.15.9'
  - fumadocs-core@16.15.9
